[package]
name = "dfs"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
publish = false

[[bin]]
name = "dfs"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.138", features = ["derive"] }
serde_yaml = "0.8.25"
serde_json = "1.0.82"
chrono = "0.4.19"
chrono-tz = { version = "0.6.1", features = ["serde"] }
regex = "1.6.0"
log = "0.4.17"

# internal deps
resolver = "^0.1"
eval-utility = "^0.1"
inflection-rs = "^0.1"

# web deps
tokio = { version = "1.19.2", features = ["full"] }
mini-redis = "0.4"
actix-files = "0.6"
actix-web = { version = "4" }
actix-cors = "0.6.1"
reqwest = "0.11.11"

