[package]
name = "dfs"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
publish = false

[[bin]]
name = "dfs"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.140", features = ["derive"] }
serde_yaml = "0.9.0"
serde_json = "^1.0"
chrono = "0.4.19"
chrono-tz = { version = "0.6.3", features = ["serde"] }
regex = "1.6.0"

tracing = "0.1.36"
tracing-subscriber = "0.3.15"

# internal deps
#resolver = { path = "../resolver" }
#eval-utility = { path = "../eval-utility" }
#inflection-rs = { path = "../inflection-rs" }
resolver = "^0.1"
eval-utility = "^0.1"
inflection-rs = "^0.1"

# web deps
tokio = { version = "1.21.1", features = ["full"] }
mini-redis = "0.4.1"
jsonwebtokens-cognito = "0.1.1"
oauth2 = "4.2.3"
openssl = "0.10.41"
actix-files = "0.6"
actix-web = { version = "4.2.1", features = ["openssl"] }
actix-cors = "0.6.2"
reqwest = { verison="0.11.11", features = ["json"] }
lazy_static = "1.4.0"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
